- hosts: localhost
  name: Creating EKS Cluster and Network Components
  vars:
    aws_region: "us-east-1"
    availability_zones:
      - "{{ aws_region }}a"
      - "{{ aws_region }}b"
    cluster_name: "Test-Cluster"
    ec2_endpoint: "com.amazonaws.{{ aws_region }}.ec2"
    ecr_api_endpoint: "com.amazonaws.{{ aws_region }}.ecr.api"
    ecr_dkr_endpoint: "com.amazonaws.{{ aws_region }}.ecr.dkr"
    eks_endpoint: com.amazonaws.{{ aws_region }}.eks
    eks_auth_endpoint: com.amazonaws.us-east-1.eks-auth
    eks_node_role_name: "EKS-Node-Policy"
    eks_role_name: "EKS-Master-Node-Policy"
    eks_version: 1.34  
    node_subnets:
      - "10.0.1.0/24"
      - "10.0.2.0/24"
    node_subnets_name:
      - "Node-Subnet-1"
      - "Node-Subnet-2"
    pod_subnets:
      - "10.0.3.0/24"
      - "10.0.4.0/24"
    pod_subnets_name:
      - "Pod-Subnet-1"
      - "Pod-Subnet-2"
    security_group_name: "EKS-Master-Node-Group"
    sts_endpoint: "com.amazonaws.{{ aws_region }}.sts"
    s3_gateway_endpoint: com.amazonaws.{{ aws_region }}.s3
    vpc_name: "EKS"
    vpc_cidr: "10.0.0.0/16" 
  tasks:
    - name: Creating EKS Infrastructure
      include_role:
        name: create_eks_infrastructure



