- hosts: localhost
  name: Delete All
  vars:
    aws_region: "us-east-1"
    cluster_name: "Test-Cluster"
    eks_role_arn: "arn:aws:iam::868077586813:role/EKS-Master-Node-Policy"
    eks_role_name: "EKS-Master-Node-Policy"
    eks_version: 1.34
    security_group_name: "EKS-Master-Node-Group"
    vpc_name: "EKS"
    vpc_cidr: "10.0.0.0/16"   
    availability_zones:
      - "us-east-1a"
      - "us-east-1b"
    node_subnets:
      - "10.0.1.0/24"
      - "10.0.2.0/24"
    node_subnets_name:
      - "Node-Subnet-1"
      - "Node-Subnet-2"
    pod_subnets:
      - "10.0.3.0/24"
      - "10.0.4.0/24"
    pod_subnets_name:
      - "Pod-Subnet-1"
      - "Pod-Subnet-2"
  tasks:
    - name: Delete All
      include_role:
        name: delete_eks_infrastructure
